### ISSUE TITLE
Update development instructions to include visual and performance tests

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core#107]
https://github.com/vaadin/vaadin-core-elements/blob/master/DEVELOPMENT.md doesn’t contain any instructions how to run the visual or performance tests.

**Comment by web-padawan** [comment]
The visual tests are now mentioned as "optional" in the [CONTRIBUTING.md](https://github.com/vaadin/vaadin-core/blob/master/CONTRIBUTING.md).

For the external PRs, the current team workflow we agreed about is to merge them into branches, to trigger visual tests, and then fix them ourselves as necessary before merging to master.
