### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core#13]
Add any elements you would like to see us build as comments to this issue.

**Comment by andrefelipe** [comment]
I'd definitely ask a **File Browser** element.

Layout could be same as Vaadin Grid, but adding the folder navigation, specially in column mode.

Folders would need to be "hot areas", to be able to accept file drop events, so devs could implement the upload feature. And of course, if you'd offer the upload integration altogether, it would be king!

Congratulations for the focus on HTML elements, your products are extremely hi-quality.

**Comment by jouni** [comment]
From vaadin.com/elements suggestion box: "Add an option to truncate large texts"

**Comment by heruan** [comment]
- Navbar component
- Card component
- Button grouping
- Button dropdown/dropup (with split option)
- Tooltips (nobody likes browser's default with `title` 😄 )

**Comment by heruan** [comment]
As requested in #60, resurrecting Calendar from FW7 into a Web Component would be awesome too! Could be a specialized `<vaadin-grid>` where the data provider provides events, with year/month/week/day views.

**Comment by tomivirkki** [comment]
Closing, prefer feature/component requests as separate issues (easier to manage & discuss)
