### ISSUE TITLE
<vaadin-notification>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-core#135]
- Notification uses a single `<vaadin-notification-overlay>` (`<vaadin-overlay>` extension)
- Opening a notification closes any currently open notification
  - Store a reference to currently open notification element as a private property in `Vaadin.NotificationElement`
  - If there is an open notification, wait a while before opening a new one so any closing animation of the previous one has a chance to finish
    - Default style doesn't need to animate
- Should be animatable (by Valo)
- Set `verticalAlign` and `horizontalAlign` values as attributes to `<vaadin-notification-overlay>` element
- Use similar positioning as `<vaadin-dialog>` (full size flexbox `<vaadin-notification-overlay>`)
  - Document pointer-events must not be overridden so you can access page content while the notification is open

MVP properties:
- `text`
- `duration` default 3000
- `horizontalAlign` default “start”
- `verticalAlign` default “end”
- `opened`

MVP functions:
- `open()`
- `close()`

Generic MVP requirements in https://sites.google.com/a/vaadin.com/elements-wiki/workflow

**Comment by platosha** [comment]
Well well well, position-bound API values like `left` are not RTL-compatible. How about `start`, `end`, `center`, `stretch` instead? Note that these align property values are is even easier to implement with `<vaadin-overlay>`, as it uses flexbox around the overlay part.

**Comment by tomivirkki** [comment]
Updated the description

**Comment by jouni** [comment]
Here are some more additional and detailed specs:


## Behavior

### Animations
Notifications should allow enter and exit animations. This would a great generic addition to `vaadin-overlay`.

Ideally, here’s what I would like to write in a theme:

```css
selector-for-the-visible-notification-element[enter] {
  animation: fade-in 300ms;
}

selector-for-the-visible-notification-element[exit] {
  animation: fade-out 600ms;
}
```

### Duration
The notification stays open for this duration (start counting after the enter animation has finished).

Clicking the notification does not close it by default (developer can add a click listener that does it if needed).
  - This behavior differs from the Vaadin Framework Notification component, where this is called “delay”, and the notification will only start counting that time after the user makes some action (mouse move, click/tap/keypress or clicking the notification itself).

Setting the duration to 0 or a negative number the notification stays on screen permanently, or until it’s closed by a script or another notification is shown (unless the notification is “persistent”, see below).

### “Persistent” notifications
An additional attribute/property to make a notification keep itself visible even if other notifications are displayed (`persist`, `priority`, `important` or something like that). The duration still affects these notifications as usual.

This makes it possible to show multiple notifications at once.


## Multiple notifications

Contrary to the current description, it should be possible (at least eventually) to have multiple notifications opened simultaneously, not just one.

Here’s a CSS proto how multiple notifications should appear and stack: http://jsbin.com/tanegiqasa
 
Notice, that the idea is to place all notifications inside the same “overlay container” which makes stacking work nicely with CSS. Not sure if this is possible somehow with `vaadin-overlay`.

(Ignore the content inside the notifications, the layout for that is just a dummy for illustration purposes.)


## HTML content

The notification should accept HTML content, not just text. 

### Content overflow

Notifications should have a max-width and allow the content to wrap.

Some users want to show long error messages in the notifications (such as full stack traces), so the notifications need to have a max height as well and allow scrolling in those situations.


## API considerations

I assume the primary API we offer is declarative, something like:
```html
<vaadin-notification duration="0" persist>
  <p>Content</p>
  <!-- Not a requirement, but a possible future slot we might add, which does not scroll with the content -->
  <vaadin-button slot="action">Dismiss</vaadin-button>
</vaadin-notification>
```

Using from JavaScript should also work:

```javascript
// Can we have constructor parameters? 
// This is possibly overkill, as `textContent/innerText` and `innerHTML` are also available
const notify = new Vaadin.NotificationElement('Content'); // or document.createElement('vaadin-notification');
notify.innerHTML = '<p>Content</p>';
document.body.appendChild(notify);
notify.show();
```

Will these work with the idea that all notifications should be placed inside a single “overlay container”?

Should we offer a “close all” method? Something like `Vaadin.NotificationElement.closeAll()`

**Comment by tomivirkki** [comment]
If we accept HTML content, a `<template>` is required as the content will not be slotted but stamped inside `<vaadin-overlay>`

**Comment by jouni** [comment]
Right, the same as with all overlay contents. Acceptable tradeoff. I’ll update the examples.

**Comment by jouni** [comment]
I’m reconsidering the need to support scrolling content – perhaps we should not encourage that kind of use cases, for which notifications are really not a good fit. Notifications should show the minimum amount of information to convey the most important info, and if the user can have more details about it, they should be able to click the notification to view more (like a full stack trace log for example).

So let’s skip scrolling content for now.

Also, I’m thinking we should reverse the default for the “persist” feature so that notifications are by default persistent (won’t go away when another notification is shown). Instead, the developer can mark a notification “transient” which means the notification will go away when any other notification is shown.
