### ISSUE TITLE
borderless button outline leaves single pixel outline on left side of button when deselected

### ISSUE THREAD

**Issue by DavidJordanJr** [vaadin/vaadin-core#145]
I have two buttons declared as large and borderless using Valo theme. Initially the buttons have no border. When I press the buttons, the borders appear and stay visible. This may or may not be expected behavior, I am new to Vaadin. When I click somewhere else in the UI outside of the button, the entire button outline is removed, but only about half the time. The other half of the time, a single pixel line on the left side of the border/outline remains on the screen. This looks like a bug.

**Comment by jouni** [comment]
Hi! A screenshot of a screen recording would be excellent to see. Which OS and browser are you using, and what versions of vaadin-button and vaadin-valo-theme?

**Comment by jouni** [comment]
Closing since there hasn’t been any activity in a long time.
