### ISSUE TITLE
IOS textfield focus

### ISSUE THREAD

**Issue by ebatgerel** [vaadin/vaadin-core#153]
When user click on search button search field appears but it is not focused. Any solution of this ?

**Comment by jouni** [comment]
There’s really not nearly enough information in this issue to be able to say anything helpful. Please describe the problem in more detail (element, version, platform, code, jsbin/fiddle reproducing the issue), so we can help. Thanks!

Also, usage questions like this are better handled in our [Gitter chat](https://gitter.im/vaadin/vaadin-core-elements) or [#vaadin Polymer Slack channel](https://polymer.slack.com/).
