### ISSUE TITLE
Rename Valo to Lumo

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-core#158]
Change all mentions of Valo to Lumo. Make sure letter casing matches. Make sure theme/valo folder has been renamed. Depend on `vaadin/vaadin-lumo-styles#^1.0.0` in elements

- [x] vaadin-lumo-styles (make public and release 1.0.0-alpha1)
- [x] vaadin-button
- [x] vaadin-checkbox
- [x] vaadin-combo-box
- [x] vaadin-context-menu
- [x] vaadin-core-elements
- [x] vaadin-date-picker
- [x] vaadin-dialog
- [x] vaadin-dropdown-menu
- [x] vaadin-element-skeleton
- [x] vaadin-form-layout
- [x] vaadin-grid
- [x] vaadin-item
- [x] vaadin-list-box
- [x] vaadin-notification
- [x] vaadin-ordered-layout
- [x] vaadin-overlay
- [x] vaadin-progress-bar
- [x] vaadin-radio-button
- [x] vaadin-split-layout
- [x] vaadin-tabs
- [x] vaadin-text-field
- [x] vaadin-upload

**Comment by jouni** [comment]
I can take care of deprecating the `vaadin-valo-styles` package and repo (adding a console warning for users to migrate to `vaadin-lumo-styles`).

**Comment by fasihrana** [comment]
Will this take care of the Google Chrome Stylesheets HTML Imports?

```[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.```

**Comment by tomivirkki** [comment]
@fasihrana Not this particular change, but we're planning on fixing the warning issue during the ongoing alpha period.

**Comment by jouni** [comment]
@fasihrana see https://github.com/Polymer/polymer/issues/5017 for more info. 

Basically, the console warning is a false positive, the styling will still work. But with the small update, it should be possible to also avoid the console warning.

**Comment by jouni** [comment]
@tomivirkki could you add tasks for unregistering `vaadin-valo-theme` from Bower and registering `vaadin-lumo-styles`.
