### ISSUE TITLE
Bower is deprecated

### ISSUE THREAD

**Issue by chvndb** [vaadin/vaadin-core#159]
Taken from their website:

> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!

Maybe, it is time Vaadin moves away from Bower.

**Comment by web-padawan** [comment]
The current generation of Vaadin Elements is built with Polymer 2.0 which relies on HTML imports and `bower` as part of the ecosystem. However, the Polymer 3.0 is expected to be released this year once ES modules get [browser support](https://caniuse.com/#feat=es6-module). There is a Polymer 3.0 [status page](https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md) recently added so you can track the progress on the official elements there. We have already tried some early prototyping but the `polymer-modulizer` converting tool is still WIP. Once its get released, and the Polymer 3.0 itself gets at least first beta, we will be happy to start working on `npm` support. We will also update the README in this repo to inform about the progress. Until then, using `bower` is the only option, so I am closing this issue.
