### ISSUE TITLE
Register vaadin-lumo-styles

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-core#160]
unregister vaadin-valo-theme from Bower and register vaadin-lumo-styles

**Comment by manolo** [comment]
This would break bakery at least until it's upgraded to a platform version that includes styled elements

**Comment by jouni** [comment]
@manolo, you can update the dependency in Bakery to use `vaadin/vaadin-valo-styles` explicitly, and nothing should break (unless you upgrade some of the elements that have the new default theme).

**Comment by manolo** [comment]
@jouni yep, updating dependency and imports works. We will update to elements with default theme soon
