### ISSUE TITLE
Bower.json uses vaadin-core 10.0.0-beta1. It should use beta9

### ISSUE THREAD

**Issue by paivisoinio** [vaadin/vaadin-core#182]
Bower.json uses vaadin-core 10.0.0-beta1. It should use beta9

**Comment by web-padawan** [comment]
The version is in `pacjage.json`. This was actually fixed in b52e9e6 (and released) but that commit is not in the master branch.

**Comment by web-padawan** [comment]
The version is now being updated correctly by the Platform team, closing.
