### ISSUE TITLE
Regression on combobox in dialog between RC2 and RC3

### ISSUE THREAD

**Issue by bisam-rd** [vaadin/vaadin-core#188]
When upgrading from RC2 to RC3, we have a regression.
Dropdown list of combo boxes in a dialog close immediatly after beeing opened by a user.
Seems to be the same with Date picker.

**Comment by pleku** [comment]
Fixed with https://github.com/vaadin/flow/pull/4269 soon to be released in RC4

**Comment by bisam-rd** [comment]
Thanks
