### ISSUE TITLE
Vaadin Flow Text Field is not null safe

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-core#191]
When I call textField.setValue( null ); it throws "Caused by: java.lang.NullPointerException: Null value is not supported". It is not usefull...

**Comment by web-padawan** [comment]
Thanks for the issue. This repo is for Web Components, and for their Java counterparts we have different repos. I will move it there so that our teammates could handle it appropriately.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-text-field-flow#94
