### ISSUE TITLE
File Upload 

### ISSUE THREAD

**Issue by andrea-tomassi** [vaadin/vaadin-core#206]
I'm successfully using the com.vaadin.flow.component.upload.Upload component in 
vaadin.version>11.0.1</vaadin.version>

I set	upload.setAutoUpload(true) and upload.addSucceededListener() is correctly invoked at the end of the upload. 

If I move to <vaadin.version>11.0.2</vaadin.version> the upload stop to work. 
After the version update, the addSucceededListener method is never called anymore. 

If I downgrade to 11.0.1 the upload component works well. 

Example code: 

```
Upload upload = new Upload(new MemoryBuffer());
upload.setAutoUpload(true);
upload.addSucceededListener(event -> {
			System.out.println("SUCCEEDED Uploading --> " + event.getMIMEType() + " [" + event.getFileName() + "]");
			this.fileName = event.getFileName();
			headerUploadWrapperDiv.add(new Label("file: " + fileName  + " uploaded."));
		});
headerUploadWrapperDiv.add(upload);
```

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-upload-flow#95
