### ISSUE TITLE
Menu/menubar component

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-core#208]
The component displays a hierarchical list of selectable items with additional config properties. The items can have a label, icon, they can be disabled/enabled, checkable, checked. Developer can also configure dividers to be placed between the items.

<img width="641" alt="menubar-lumo" src="https://user-images.githubusercontent.com/1222264/53014336-dbbaef00-3450-11e9-9e60-c261fb3fa156.png">

For reference, V8 Menubar component [here](https://demo.vaadin.com/sampler/#ui/interaction/menu-bar)

**Comment by heruan** [comment]
It would be useful for the menu component to target any "root" component, such as text, buttons, avatars, etc.

For example like the GitHub "user menu" in the navigation bar:

<img width="217" alt="screenshot 2018-12-12 at 15 20 12" src="https://user-images.githubusercontent.com/851745/49928559-af1eb000-fec0-11e8-81b2-67dbb5e0e3c9.png">

**Comment by tomivirkki** [comment]
The nested menu support will be implemented for context menu first https://github.com/vaadin/vaadin-context-menu/issues/124 That can be used as a generic menu for any root component. 

We might still need to build an additional helper component to make positioning of the dropdown menu easier however.
