### ISSUE TITLE
Make a scrollable layout with Java API.

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-core#217]
Today, if you want to have content that can be scrolled, you don't have any easy way to do that i Flow. The best way to do that is 

```
Div div = new Div();
div.getElement().getStyle().set("overflow", "auto");
```

The use case (scrolling panel) is very common on the web, and that code above does not reek "best practice". Vaadin should provide a ready made solution for it.

One option would be to provide a ScrollPanel component that is really just a Div with overflow: auto and similar. 100% width and height would be nice as well.

**Comment by rolfsmeds** [comment]
An API for setting horizontal and vertical scrolling separately would also be useful.
Maybe also for toggling whether scrollbars are always visible (`:scroll`) or only when needed (`:auto`)

**Comment by rolfsmeds** [comment]
An API for setting the scrollposition, or even better, scrolling a particular component into view, would also be very useful.

**Comment by alvarezguille** [comment]
ScrollContainer added in https://github.com/vaadin/vaadin-ordered-layout-flow/pull/116
Targeted versions:
* vaadin-ordered-layout-flow 2.1 in Vaadin 14.2
* vaadin-ordered-layout-flow 3.1 in Vaadin 16
