### ISSUE TITLE
vaadin-core.js should import drawer toggle (?)

### ISSUE THREAD

**Issue by eiswind** [vaadin/vaadin-core#229]
import '@vaadin/vaadin-app-layout/vaadin-drawer-toggle'; seems to be missing.

is it intended that this one is not imported by default?

**Comment by web-padawan** [comment]
Thank you. Moved the issue to the corresponding repository.

**Comment by web-padawan** [comment]
Fixed for 14.1, will cherry-pick to 14.2 and then later to master when we fix CI build.

**Comment by web-padawan** [comment]
Cherry-picked to 14.2. Will close after we fix this on master branch.
