### ISSUE TITLE
Chrome freezes in views with several nested layouts

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-core#258]
Several components with popup (like ComboBox, Select, DatePicker) seem to cause Chrome to freeze in views with several nested layouts. For example, the following snippet reproduces the issue reliably in Chrome (Version 84.0.4147.105). For other browsers (Firefox, Edge, Chromium, Opera), the same view works flawlessly.

```
@Route("")
public class NestedView extends Div
{
    public NestedView()
    {
        FlexLayout topPanel = new FlexLayout();
        FlexLayout cVp = topPanel;
        for (int i = 0; i < 20; i++)
        {
            FlexLayout p = new FlexLayout();
            p.getElement().getStyle().set("flex-direction", "column");
            DatePicker select = new DatePicker();
            p.add(select);
            cVp.add(p);
            cVp = p;
        }
        add(topPanel);
    }
}
```

The issue was reproducible at least in Vaadin versions 14.3.0 and 14.2.0.

**Comment by tomivirkki** [comment]
It's a Chromium issue and related to `pointer-events: none`.
Here's an isolated, plain html example: https://jsbin.com/jojunexixa/edit?html,output

One possible (but bad) workaround is to add
```html
<style>
    body {
      pointer-events: auto !important;
    }
</style>
```
to your app. It has a nasty drawback though: You're not supposed to be able to click other parts of the UI while a combo-box dropdown etc is open. This workaround cancels that behaviour.

**Comment by tomivirkki** [comment]
The bug is fixed in Chrome 85, which is scheduled for release on Aug 25

**Comment by tomivirkki** [comment]
Chrome 85 is now released so closing this
