### ISSUE TITLE
Semantics of using the same components as helpers are unclear

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-core#260]
Tested with V14.4.0.alpha1 and the bookstore example:
In `ProductForm.java` I added 

```
        Image img = new Image("https://vaadin.com/images/vaadin-logo.svg","Vaadin logo");
        img.setWidth("180px");
        img.setHeight("100px");
        productName.setHelperComponent(img);
        ...
        price.setHelperComponent(img);

```

I get
![image](https://user-images.githubusercontent.com/19165931/92582933-e38bef80-f291-11ea-86b4-4f91a5c6df0f.png)

I would have expected that either I get the image below both components (preferred!) or at least have a note in the javadoc that only the last called component gets the child.

**Comment by tomivirkki** [comment]
As mentioned by @jcgueriaud1 , the same component can't be added twice. This isn't specific to the component but Vaadin in general. Closing as wontfix
