### ISSUE TITLE
Strip comments from the CDN version of all elements

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core#31]
There’s no reason to make CDN users download the comments. Removing them could speed up the download at least some.

**Comment by samiheikki** [comment]
I'm in favor of closing this. If comments were stripped, the Polymer generated documentation sites would not work. I think better option would be adding `.min.html` versions to cdn.

**Comment by jouni** [comment]
Yeah, you’re right. Since we are using the CDN hosted API docs on vaadin.com, we can’t strip those.

A min.html could work instead, and we could use those files in our demos/examples, to make it faster to load them on vaadin.com.
